import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Nav/NavBar";
import { ThemeProvider } from "@/components/Themes/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "News Description",
  description: "Generated by Joshardals Gates",
};

export const dynamic = "force-dynamic";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <section className="max-w-[50rem] mx-auto p-5">
            <div className="mt-10">
              <NavBar />
            </div>

            <main>{children}</main>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
